version: '3.1'

services:

  postgres:
          image: postgres
          environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: a.123456
          ports:
            - 5432:5432
          restart: unless-stopped

  pgadmin:
          image: dpage/pgadmin4
          environment:
            - PGADMIN_DEFAULT_EMAIL=user@domain.com
            - PGADMIN_DEFAULT_PASSWORD=a.123456
            - PGADMIN_LISTEN_PORT=80
          depends_on:
          - postgres
          ports:
          - 8050:80
          restart: unless-stopped